name: scgen-repro-env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.2.15.3
  - annotated-types=0.7.0
  - anyio=4.12.1
  - appdirs=1.4.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.1.0
  - attrs=25.4.0
  - babel=2.17.0
  - backports=1.0
  - backports.tarfile=1.2.0
  - backports.zstd=1.3.0
  - beautifulsoup4=4.14.3
  - binutils=2.45
  - binutils_impl_linux-64=2.45
  - binutils_linux-64=2.45
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - boltons=25.0.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - c-compiler=1.11.0
  - ca-certificates=2026.1.4
  - cachecontrol=0.14.3
  - cachecontrol-with-filecache=0.14.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - click-default-group=1.2.4
  - colorama=0.4.6
  - comm=0.2.3
  - compilers=1.11.0
  - conda-gcc-specs=14.3.0
  - conda-lock=4.0.0
  - conda-package-streaming=0.12.0
  - contourpy=1.3.2
  - crashtest=0.4.1
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - curl=8.18.0
  - cxx-compiler=1.11.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - debugpy=1.8.20
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distlib=0.4.0
  - double-conversion=3.4.0
  - dulwich=0.24.10
  - ensureconda=1.6.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - fbpca=1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - fortran-compiler=1.11.0
  - fqdn=1.5.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gcc=14.3.0
  - gcc_impl_linux-64=14.3.0
  - gcc_linux-64=14.3.0
  - gfortran=14.3.0
  - gfortran_impl_linux-64=14.3.0
  - gfortran_linux-64=14.3.0
  - git=2.53.0
  - gitdb=4.0.12
  - gitpython=3.1.46
  - glpk=5.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - gsl=2.7
  - gxx=14.3.0
  - gxx_impl_linux-64=14.3.0
  - gxx_linux-64=14.3.0
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - intervaltree=3.1.0
  - ipython=8.37.0
  - ipywidgets=8.1.8
  - isoduration=20.11.0
  - jaraco.classes=3.4.0
  - jaraco.context=6.1.0
  - jaraco.functools=4.4.0
  - jedi=0.19.2
  - jeepney=0.9.0
  - jinja2=3.1.6
  - joblib=1.5.3
  - json5=0.13.0
  - jsonpointer=3.0.0
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.26.0
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.8.0
  - jupyter_console=6.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.4
  - jupyterlab=4.5.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - kernel-headers_linux-64=5.14.0
  - keyring=25.7.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.1
  - lcms2=2.18
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang-cpp21.1=21.1.8
  - libclang13=21.1.8
  - libcups=2.3.3
  - libcurl=8.18.0
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=14.3.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libllvm21=21.1.8
  - liblzma=5.8.2
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.54
  - libpq=18.1
  - libsanitizer=14.3.0
  - libsodium=1.0.20
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=14.3.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.3
  - libuv=1.51.0
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - make=4.4.1
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mistune=3.2.0
  - more-itertools=10.8.0
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - nbclient=0.10.4
  - nbconvert-core=7.17.0
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.5.3
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.1
  - overrides=7.7.0
  - packaging=26.0
  - pandas=2.3.3
  - pandoc=3.9
  - pandocfilters=1.5.0
  - pango=1.56.4
  - parso=0.8.5
  - pcre2=10.47
  - perl=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=12.1.0
  - pip=26.0
  - pixman=0.46.4
  - pkginfo=1.12.1.2
  - platformdirs=4.5.1
  - prometheus_client=0.24.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.2.2
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pyparsing=3.3.2
  - pyproject_hooks=1.2.0
  - pyside6=6.10.1
  - pysocks=1.7.1
  - python=3.10.19
  - python-annoy=1.17.3
  - python-build=1.4.0
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-installer=0.7.0
  - python-json-logger=2.0.7
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.10.1
  - r-abind=1.4_8
  - r-askpass=1.2.1
  - r-base=4.5.2
  - r-base64enc=0.1_6
  - r-bh=1.90.0_1
  - r-bitops=1.0_9
  - r-bslib=0.10.0
  - r-cachem=1.1.0
  - r-catools=1.18.3
  - r-cli=3.6.5
  - r-cluster=2.1.8.2
  - r-codetools=0.2_20
  - r-colorspace=2.1_2
  - r-commonmark=2.0.0
  - r-cowplot=1.2.0
  - r-cpp11=0.5.3
  - r-crayon=1.5.3
  - r-crosstalk=1.2.2
  - r-curl=7.0.0
  - r-data.table=1.17.8
  - r-deldir=2.0_4
  - r-digest=0.6.39
  - r-dotcall64=1.2
  - r-dplyr=1.2.0
  - r-dqrng=0.3.2
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.5
  - r-fansi=1.0.7
  - r-farver=2.1.2
  - r-fastdummies=1.7.5
  - r-fastmap=1.2.0
  - r-fitdistrplus=1.2_6
  - r-fnn=1.1.4.1
  - r-fontawesome=0.5.3
  - r-fs=1.6.6
  - r-future=1.69.0
  - r-future.apply=1.20.1
  - r-generics=0.1.4
  - r-ggplot2=4.0.2
  - r-ggrepel=0.9.6
  - r-ggridges=0.5.7
  - r-globals=0.19.0
  - r-glue=1.8.0
  - r-goftest=1.2_3
  - r-gplots=3.3.0
  - r-gridextra=2.3
  - r-gtable=0.3.6
  - r-gtools=3.9.5
  - r-here=1.0.2
  - r-hexbin=1.28.5
  - r-highr=0.11
  - r-htmltools=0.5.9
  - r-htmlwidgets=1.6.4
  - r-httpuv=1.6.16
  - r-httr=1.4.8
  - r-ica=1.0_3
  - r-igraph=2.1.4
  - r-irlba=2.3.7
  - r-isoband=0.3.0
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-kernsmooth=2.23_26
  - r-knitr=1.51
  - r-labeling=0.4.3
  - r-later=1.4.6
  - r-lattice=0.22_9
  - r-lazyeval=0.2.2
  - r-leidenbase=0.1.36
  - r-lifecycle=1.0.5
  - r-listenv=0.10.0
  - r-lmtest=0.9_40
  - r-magrittr=2.0.4
  - r-mass=7.3_65
  - r-matrix=1.7_4
  - r-matrixstats=1.5.0
  - r-memoise=2.0.1
  - r-mime=0.13
  - r-miniui=0.1.2
  - r-munsell=0.5.1
  - r-nlme=3.1_168
  - r-openssl=2.3.4
  - r-otel=0.2.0
  - r-parallelly=1.46.1
  - r-patchwork=1.3.2
  - r-pbapply=1.7_4
  - r-pillar=1.11.1
  - r-pkgconfig=2.0.3
  - r-plotly=4.12.0
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-polyclip=1.10_7
  - r-progressr=0.18.0
  - r-promises=1.5.0
  - r-purrr=1.2.1
  - r-r6=2.6.1
  - r-rann=2.6.2
  - r-rappdirs=0.3.4
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.1.1
  - r-rcppannoy=0.0.23
  - r-rcpparmadillo=15.2.3_1
  - r-rcppeigen=0.3.4.0.2
  - r-rcpphnsw=0.6.0
  - r-rcppprogress=0.4.2
  - r-rcpptoml=0.2.3
  - r-reshape2=1.4.5
  - r-reticulate=1.45.0
  - r-rlang=1.1.7
  - r-rmarkdown=2.30
  - r-rocr=1.0_12
  - r-rprojroot=2.1.1
  - r-rspectra=0.16_2
  - r-rtsne=0.17
  - r-s7=0.2.1
  - r-sass=0.4.10
  - r-scales=1.4.0
  - r-scattermore=1.2
  - r-sctransform=0.4.3
  - r-seurat=5.4.0
  - r-seuratobject=5.3.0
  - r-shiny=1.12.1
  - r-sitmo=2.0.2
  - r-sourcetools=0.1.7_1
  - r-sp=2.2_1
  - r-spam=2.11_3
  - r-spatstat.data=3.1_9
  - r-spatstat.explore=3.7_0
  - r-spatstat.geom=3.7_0
  - r-spatstat.random=3.4_4
  - r-spatstat.sparse=3.1_0
  - r-spatstat.univar=3.1_6
  - r-spatstat.utils=3.2_1
  - r-stringi=1.8.7
  - r-stringr=1.6.0
  - r-survival=3.8_6
  - r-sys=3.4.3
  - r-tensor=1.5.1
  - r-tibble=3.3.1
  - r-tidyr=1.3.2
  - r-tidyselect=1.2.1
  - r-tinytex=0.58
  - r-utf8=1.2.6
  - r-uwot=0.2.4
  - r-vctrs=0.7.1
  - r-viridislite=0.4.3
  - r-withr=3.0.2
  - r-xfun=0.56
  - r-xtable=1.8_4
  - r-yaml=2.3.12
  - r-zoo=1.8_15
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.30.0
  - rpy2=3.6.4
  - ruamel.yaml=0.19.1
  - ruamel.yaml.clib=0.2.15
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - secretstorage=3.4.1
  - sed=4.9
  - semver=3.0.4
  - send2trash=2.1.0
  - setuptools=80.10.2
  - shellingham=1.5.4
  - six=1.17.0
  - smmap=5.0.2
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.8.3
  - stack_data=0.6.3
  - sysroot_linux-64=2.34
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tktable=2.10
  - tomli=2.4.0
  - tomlkit=0.14.0
  - tornado=6.5.4
  - traitlets=5.14.3
  - trove-classifiers=2026.1.14.14
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025c
  - tzlocal=5.3.1
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - urllib3=2.6.3
  - vim=9.1.1858
  - virtualenv=20.36.1
  - wayland=1.24.0
  - wcwidth=0.5.3
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.46.3
  - widgetsnbextension=4.0.15
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.5
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.7
  - xorg-xorgproto=2025.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.4.0
      - adjusttext==1.3.0
      - anndata==0.11.4
      - argcomplete==2.1.2
      - array-api-compat==1.13.0
      - astunparse==1.6.3
      - bbknn==1.6.0
      - cloudpickle==3.1.2
      - cryptography==46.0.4
      - cython==3.2.4
      - entrypoints==0.4
      - filelock==3.20.3
      - flatbuffers==25.12.19
      - future==1.0.0
      - gast==0.4.0
      - gdown==5.2.1
      - google-auth==2.48.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - hyperas==0.4.1
      - hyperopt==0.2.7
      - igraph==0.11.9
      - ipykernel==7.2.0
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - legacy-api-wrap==1.5
      - libclang==18.1.1
      - llvmlite==0.46.0
      - louvain==0.8.2
      - markdown==3.10.1
      - natsort==8.4.0
      - networkx==3.4.2
      - numba==0.63.1
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - patsy==1.0.2
      - protobuf==3.19.6
      - py4j==0.10.9.9
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pynndescent==0.6.0
      - requests-oauthlib==2.0.0
      - rpy2-rinterface==3.6.3
      - rpy2-robjects==3.6.3
      - rsa==4.9.1
      - scanpy==1.11.5
      - seaborn==0.13.2
      - session-info2==0.3
      - statsmodels==0.14.6
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.3.0
      - texttable==1.7.0
      - tinycss2==1.4.0
      - tqdm==4.67.2
      - umap-learn==0.5.11
      - werkzeug==3.1.5
      - wget==3.2
      - wrapt==2.1.0
