#!/bin/bash
# Create symlink from Jupyter Notebooks/scgen to code/scgen (Linux)

set -e  # Exit on error

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

NOTEBOOKS_SCGEN="$REPO_ROOT/Jupyter Notebooks/scgen"
CODE_SCGEN="$REPO_ROOT/code/scgen"

cd "$REPO_ROOT"

# Remove existing duplicate directory if it exists
if [ -d "$NOTEBOOKS_SCGEN" ] && [ ! -L "$NOTEBOOKS_SCGEN" ]; then
    echo "Removing duplicate scgen directory..."
    rm -rf "$NOTEBOOKS_SCGEN"
fi

# Create symlink if it doesn't exist
if [ ! -e "$NOTEBOOKS_SCGEN" ]; then
    echo "Creating symlink from 'Jupyter Notebooks/scgen' to 'code/scgen'..."
    ln -s "../code/scgen" "$NOTEBOOKS_SCGEN"
    echo "Symlink created successfully!"
else
    echo "Symlink or directory already exists at 'Jupyter Notebooks/scgen'"
    echo "Skipping symlink creation."
fi

# Install an IPython startup hook (SageMaker/Jupyter friendly, one-time).
# This sets notebook cwd and sys.path without requiring notebook edits.
IPY_STARTUP_DIR="$HOME/.ipython/profile_default/startup"
IPY_HOOK_FILE="$IPY_STARTUP_DIR/00-scgen_bootstrap.py"
mkdir -p "$IPY_STARTUP_DIR"
cat > "$IPY_HOOK_FILE" <<EOF
# Auto-generated by scripts/create_symlink.sh
import os
import sys

_repo = r"$REPO_ROOT"
_nb_dir = os.path.join(_repo, "Jupyter Notebooks")
_code_dir = os.path.join(_repo, "code")

if os.path.isdir(_code_dir) and _code_dir not in sys.path:
    sys.path.insert(0, _code_dir)

if os.path.isdir(_nb_dir):
    os.chdir(_nb_dir)

if "R_HOME" not in os.environ:
    _r_home = os.path.join(sys.prefix, "lib", "R")
    if os.path.isdir(_r_home):
        os.environ["R_HOME"] = _r_home
EOF

echo "Added IPython startup hook ($IPY_HOOK_FILE). Restart the kernel or open a new terminal for changes to apply."
