#!/bin/bash
# Set up notebook environment:
# - notebook symlink
# - IPython startup hook
# - conda env activation hooks (LD_LIBRARY_PATH)
# - Jupyter kernel registration
# - optional Scanorama bootstrap (clone + 4panc files)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
NOTEBOOKS_DIR="$REPO_ROOT/Jupyter Notebooks"
NOTEBOOKS_SCGEN="$NOTEBOOKS_DIR/scgen"
CODE_SCGEN="$REPO_ROOT/code/scgen"
SYMLINK_TARGET_REL="../code/scgen"
KERNEL_NAME="scgen-repro-env"
KERNEL_DISPLAY_NAME="Python (scgen-repro-env)"
IPY_STARTUP_DIR="$HOME/.ipython/profile_default/startup"
IPY_HOOK_FILE="$IPY_STARTUP_DIR/00-scgen_bootstrap.py"
SCANORAMA_REPO_URL="https://github.com/brianhie/scanorama.git"
SCANORAMA_DIR="$(cd "$REPO_ROOT/.." && pwd)/scanorama"
SCANORAMA_CONF_FILE="$SCANORAMA_DIR/conf/4panc.txt"
SCANORAMA_SCRIPT_FILE="$SCANORAMA_DIR/bin/4panc.py"

ENABLE_SCANORAMA_BOOTSTRAP=1
FORCE_SCANORAMA_FILES=0

log() {
    echo "[setup-notebook-env] $*"
}

warn() {
    echo "[setup-notebook-env] WARNING: $*" >&2
}

usage() {
    cat <<EOF
Usage: $(basename "$0") [options]

Options:
  --skip-scanorama         Skip Scanorama clone + 4panc file bootstrap.
  --scanorama-dir PATH     Override Scanorama target directory (default: sibling ../scanorama).
  --force-scanorama-files  Overwrite existing conf/4panc.txt and bin/4panc.py.
  -h, --help               Show this help message.
EOF
}

parse_args() {
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --skip-scanorama)
                ENABLE_SCANORAMA_BOOTSTRAP=0
                ;;
            --scanorama-dir)
                if [ "$#" -lt 2 ]; then
                    warn "--scanorama-dir requires a value."
                    exit 2
                fi
                SCANORAMA_DIR="$2"
                SCANORAMA_CONF_FILE="$SCANORAMA_DIR/conf/4panc.txt"
                SCANORAMA_SCRIPT_FILE="$SCANORAMA_DIR/bin/4panc.py"
                shift
                ;;
            --force-scanorama-files)
                FORCE_SCANORAMA_FILES=1
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                warn "Unknown option: $1"
                usage
                exit 2
                ;;
        esac
        shift
    done
}

ensure_python_available() {
    if ! command -v python >/dev/null 2>&1; then
        log "Skipping Python-dependent setup: python command not found."
        return 1
    fi
    return 0
}

create_scgen_symlink() {
    if [ ! -d "$CODE_SCGEN" ]; then
        log "Expected source directory missing: $CODE_SCGEN"
        exit 1
    fi
    mkdir -p "$NOTEBOOKS_DIR"

    if [ -d "$NOTEBOOKS_SCGEN" ] && [ ! -L "$NOTEBOOKS_SCGEN" ]; then
        log "Removing duplicate scgen directory at '$NOTEBOOKS_SCGEN'."
        rm -rf "$NOTEBOOKS_SCGEN"
    fi

    if [ ! -e "$NOTEBOOKS_SCGEN" ]; then
        log "Creating symlink '$NOTEBOOKS_SCGEN' -> '$SYMLINK_TARGET_REL'."
        ln -s "$SYMLINK_TARGET_REL" "$NOTEBOOKS_SCGEN"
        log "Symlink created."
    else
        log "Symlink or directory already exists at '$NOTEBOOKS_SCGEN'; skipping."
    fi
}

install_ipython_startup_hook() {
    mkdir -p "$IPY_STARTUP_DIR"
    cat > "$IPY_HOOK_FILE" <<EOF
# Auto-generated by scripts/setup_notebook_environment.sh
import os
import sys

_repo = r"$REPO_ROOT"
_nb_dir = os.path.join(_repo, "Jupyter Notebooks")
_code_dir = os.path.join(_repo, "code")

if os.path.isdir(_code_dir) and _code_dir not in sys.path:
    sys.path.insert(0, _code_dir)

if os.path.isdir(_nb_dir):
    os.chdir(_nb_dir)

if "R_HOME" not in os.environ:
    _r_home = os.path.join(sys.prefix, "lib", "R")
    if os.path.isdir(_r_home):
        os.environ["R_HOME"] = _r_home
EOF

    log "Installed IPython startup hook: $IPY_HOOK_FILE"
}

install_conda_env_ld_library_hooks() {
    # Keep LD_LIBRARY_PATH env-scoped so native deps (e.g., R libs) resolve predictably.
    if [ -z "${CONDA_PREFIX:-}" ]; then
        log "Skipping LD_LIBRARY_PATH hooks: no active conda environment (CONDA_PREFIX is unset)."
        return
    fi

    local activate_dir="$CONDA_PREFIX/etc/conda/activate.d"
    local deactivate_dir="$CONDA_PREFIX/etc/conda/deactivate.d"
    local activate_hook="$activate_dir/scgen_env_vars.sh"
    local deactivate_hook="$deactivate_dir/scgen_env_vars.sh"

    mkdir -p "$activate_dir" "$deactivate_dir"

    cat > "$activate_hook" <<'EOF'
# Auto-generated by scripts/setup_notebook_environment.sh
# Keep env-specific shared libraries discoverable (e.g., libR, libstdc++).
if [ -n "${CONDA_PREFIX:-}" ]; then
    export _SCGEN_OLD_LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}"
    if [ -n "${LD_LIBRARY_PATH:-}" ]; then
        export LD_LIBRARY_PATH="${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH}"
    else
        export LD_LIBRARY_PATH="${CONDA_PREFIX}/lib"
    fi
fi
EOF

    cat > "$deactivate_hook" <<'EOF'
# Auto-generated by scripts/setup_notebook_environment.sh
if [ -n "${_SCGEN_OLD_LD_LIBRARY_PATH+x}" ]; then
    export LD_LIBRARY_PATH="${_SCGEN_OLD_LD_LIBRARY_PATH}"
    unset _SCGEN_OLD_LD_LIBRARY_PATH
else
    unset LD_LIBRARY_PATH
fi
EOF

    log "Configured env-specific LD_LIBRARY_PATH hooks:"
    log "  - $activate_hook"
    log "  - $deactivate_hook"
    log "Reactivate the environment for LD_LIBRARY_PATH changes to take effect."
}

register_jupyter_kernel() {
    if ! python -c "import ipykernel" >/dev/null 2>&1; then
        log "Skipping kernel registration: ipykernel is not installed in the active environment."
        return
    fi

    # This is intentionally idempotent: reruns update the existing kernel spec.
    log "Registering Jupyter kernel '$KERNEL_NAME'..."
    python -m ipykernel install --user --name "$KERNEL_NAME" --display-name "$KERNEL_DISPLAY_NAME"
    log "Kernel registered as '$KERNEL_DISPLAY_NAME'."
}

write_scanorama_conf_file() {
    # Paths intentionally omit .txt so scanorama/bin/process.py can append extensions.
    cat > "$SCANORAMA_CONF_FILE" <<'EOF'
data/4panc/baron
data/4panc/muraro
data/4panc/segerstolpe
data/4panc/wang
EOF
    log "Wrote Scanorama config: $SCANORAMA_CONF_FILE"
}

write_scanorama_4panc_script() {
    # Keep this script minimal: only import symbols we actually use.
    cat > "$SCANORAMA_SCRIPT_FILE" <<'EOF'
import time
from datetime import timedelta

from sklearn.preprocessing import normalize

from process import load_names, save_datasets
from scanorama import correct


data_names = [
    "data/4panc/baron",
    "data/4panc/muraro",
    "data/4panc/segerstolpe",
    "data/4panc/wang",
]


if __name__ == "__main__":
    datasets, genes_list, _ = load_names(data_names)
    t1 = time.time()
    datasets, genes = correct(datasets, genes_list)
    datasets = [normalize(ds, axis=1) for ds in datasets]
    t2 = time.time()
    print("Took " + str(timedelta(seconds=t2 - t1)))
    save_datasets(datasets, genes, data_names)
EOF
    log "Wrote Scanorama script: $SCANORAMA_SCRIPT_FILE"
}

bootstrap_scanorama_assets() {
    if [ "$ENABLE_SCANORAMA_BOOTSTRAP" -ne 1 ]; then
        log "Skipping Scanorama bootstrap by request (--skip-scanorama)."
        return
    fi

    if ! command -v git >/dev/null 2>&1; then
        warn "git not found; skipping Scanorama clone/bootstrap."
        return
    fi

    if [ ! -d "$SCANORAMA_DIR/.git" ]; then
        if [ -e "$SCANORAMA_DIR" ]; then
            warn "Scanorama directory exists but is not a git repo: $SCANORAMA_DIR"
            warn "Will not clone; continuing to create/verify conf and bin files if possible."
        else
            log "Cloning Scanorama into: $SCANORAMA_DIR"
            git clone "$SCANORAMA_REPO_URL" "$SCANORAMA_DIR"
        fi
    else
        log "Scanorama repo already present at: $SCANORAMA_DIR"
    fi

    mkdir -p "$SCANORAMA_DIR/conf" "$SCANORAMA_DIR/bin"

    if [ -f "$SCANORAMA_CONF_FILE" ] && [ "$FORCE_SCANORAMA_FILES" -ne 1 ]; then
        log "Found existing file; leaving unchanged: $SCANORAMA_CONF_FILE"
    else
        write_scanorama_conf_file
    fi

    if [ -f "$SCANORAMA_SCRIPT_FILE" ] && [ "$FORCE_SCANORAMA_FILES" -ne 1 ]; then
        log "Found existing file; leaving unchanged: $SCANORAMA_SCRIPT_FILE"
    else
        write_scanorama_4panc_script
    fi
}

main() {
    parse_args "$@"
    cd "$REPO_ROOT"
    create_scgen_symlink
    install_ipython_startup_hook

    if ensure_python_available; then
        install_conda_env_ld_library_hooks
        register_jupyter_kernel
    fi

    bootstrap_scanorama_assets
}

main "$@"
